### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by abrizu** [abrizu/scrum-github-practice#1]
**User Story:**

As a student of Eastern Michigan University, I want a precise and detailed view of my grades including assignment and test organization, so that I am able to identify my status within the classroom.

- Persona: Student who wants a detailed view of their grades
- Feature: Test and assignment organization when viewing
- Business Value: Student will identify where they stand in terms of grades

**Task List**

- [ ] Design a database to store, access, and retrieve information about student grades
- [ ] Implement a data structure responsible for organizing and calculating assignment and test data 
- [ ] Design a responsive user interface to fetch and display student grades 

**Acceptance Criteria**

1. Must display data only from the current semester
2. Viewable from the school webpage "emich.edu/student-id/grades"
3. Works optimally with Opera GX but compatible with other browsers

**Acceptance Tests**

1. Student can view total grades from all sources
2. Student can view grades only in the "Assignments" category
3. Student can view grades only in the "Tests" category
